### ISSUE TITLE
引用会报错

### ISSUE THREAD

**Issue by vistier** [baijunjie/react-native-input-scroll-view#1]
项目中package指定了rn版本, 在非他版本使用空间会出现package冲突
```
Duplicate module name: ReactNativeFiber-dev
Duplicate module name: Sample
Duplicate module name: BackHandler
```

我自己的解决方案是删除 ```node_modules/react-native-input-scroll-view/node_modules/react-native```
修改```node_modules/react-native-input-scroll-view/package.json```
``` dependencies```=>```devDependencies```

**Comment by baijunjie** [comment]
了解了，我会修改这个问题
