### ISSUE TITLE
iOS Accessory Bar

### ISSUE THREAD

**Issue by luco** [baijunjie/react-native-input-scroll-view#10]
Hey, thanks for this plugin. Seems very promising!
I have a little issue here. It works as expected on iOS, however, my input, due (I think) the accessory bar never gets visible.

![image](https://user-images.githubusercontent.com/246373/32014653-71f34e84-b99d-11e7-9ff3-9a7ca2006eaa.png)

Any thoughts on this? This happens also on numeric input, with the new accessory bar for numeric input. And sometimes the input doesn't get the focus.

**Comment by baijunjie** [comment]
I've never seen Accessory Bar at ReactNative App, it seems usually only appears in WebView?

In addition, about sometimes doesn't get the focus, whether it can provide a more detailed description of the problem?

**Comment by baijunjie** [comment]
There's no more feedback

**Comment by luco** [comment]
@baijunjie No, it's not a webview. It's a textinput.

**Comment by pleportz** [comment]
I had a similar issue. What did the trick for me was 
`<InputScrollView contentContainerStyle={{ paddingBottom: 72 }}>`

You might need to adapt the padding value :)
