### ISSUE TITLE
Doesn't work on Android

### ISSUE THREAD

**Issue by outaTiME** [baijunjie/react-native-input-scroll-view#12]
Hi guys, it doesn't work on android but works perfect on iOS, here the code, anything wrong?

```js
import React, { Component } from 'react';
import {
  StyleSheet,
  TextInput,
} from 'react-native';
import InputScrollView from 'react-native-input-scroll-view'; // 1.5.1

export default class App extends Component {
  render() {
    return (
      <InputScrollView>
        {Array(20)
          .fill()
          .map((_, i) => (
            <TextInput
              key={i}
              underlineColorAndroid="transparent"
              style={styles.text}
              placeholder={`Text ${i + 1}`}
            />
          ))}
      </InputScrollView>
    );
  }
}

const styles = StyleSheet.create({
  text: {
    height: 40,
    borderColor: 'gray',
    borderWidth: 1,
    marginBottom: 16,
    // paddingVertical: 4,
    paddingHorizontal: 8,
  },
});
```

Here the capture in both:

![screen recording 2017-11-08 at 04 59 pm](https://user-images.githubusercontent.com/140472/32571491-580c5eb6-c4a6-11e7-8009-59a2f64fb94f.gif)

**Comment by baijunjie** [comment]
Yes, you are right, android devices are not fully supported, this is my next task.

**Comment by EsdrasEtrenne** [comment]
Looks like something KeyboardAvoidingView could solve

https://facebook.github.io/react-native/docs/keyboardavoidingview.html

**Comment by baijunjie** [comment]
@outaTiME Try v1.6.0

**Comment by outaTiME** [comment]
Great @baijunjie I will check tonight ... thanks !!!

**Comment by outaTiME** [comment]
Hi again guy, im doing a new test today using Expo v33 and still no luck, here the example:

https://snack.expo.io/@outatime/form-into-scrollview

(try to click on multiline text field and keyboard overlaps textarea), any advice, thanks !!!
