### ISSUE TITLE
加了之后点击就不动了，你们有遇到这个问题吗

### ISSUE THREAD

**Issue by mmorcc** [baijunjie/react-native-input-scroll-view#14]

**Comment by baijunjie** [comment]
能提供详细的问题描述吗？包括你的环境版本

**Comment by mmorcc** [comment]
{
	"name": "xxx",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"antd-mobile": "^2.0.3",
		"react": "16.0.0-alpha.6",
		"react-native": "0.44.3",
		"react-native-android-wv-video": "^1.1.1",
		"react-native-drawer": "^2.5.0",
		"react-native-router-flux": "^4.0.0-beta.24",
		"react-native-vector-icons": "^4.4.2",
		"realm": "^2.0.12"
	},
	"devDependencies": {
		"babel-jest": "21.2.0",
		"babel-plugin-import": "^1.6.2",
		"babel-preset-react-native": "4.0.0",
		"jest": "21.2.1",
		"react-test-renderer": "16.0.0-alpha.6"
	},
	"jest": {
		"preset": "react-native"
	}
}

**Comment by baijunjie** [comment]
react-native 的版本必须在 0.46 以上
