### ISSUE TITLE
RTCShadowTextField is not a descendent of RCTScrollContentShadowView

### ISSUE THREAD

**Issue by auaden** [baijunjie/react-native-input-scroll-view#15]
Hi there, encountered this issue when using TextInput (without InputScrollView) on another screen.

Steps to reproduce:
> Screen 1 (with InputScrollView) 
> stack-navigate to screen 2 
> Crashes when TextInput(without InputScrollView) on screen 2 is tapped. 

The error screen is shown here:

<img width="409" alt="screen shot 2017-12-12 at 12 34 46 pm" src="https://user-images.githubusercontent.com/18056500/33867870-62ceed6a-df3a-11e7-8c97-c0a3ea139142.png">

Error is solved by removing InputScrollView on screen 1. 

Any advice on how to solve this? Thanks!

**Comment by auaden** [comment]
I've solved the issue. 
For anyone with the same issue, it's because the two scroll views are listening to the same keyboard. Hence, before you navigate to the second screen, you need to de-register the keyboard. My solution is: 

At the InputScrollView component:
`<InputScrollView ref={(ref) => { this.inputScrollView = ref }}>`

and do this BEFORE you navigate to the second screen with another TextInput:
`this.inputScrollView._removeListener()`

**Comment by luco** [comment]
Shouldn't this be automatic?

**Comment by Aleksandar-FFWD** [comment]
@luco I was looking into this problem. I might have found a solution.

I'll post a PR soon when I test if it works on IOS as well as on Android.

**Comment by luco** [comment]
@Aleksandar-FFWD Thanks!
