### ISSUE TITLE
Doesn't work on 0.44.3

### ISSUE THREAD

**Issue by luco** [baijunjie/react-native-input-scroll-view#17]
When trying this on 0.44.3 it simply doesn't work. It doesn't let me focus on inputs, custom or default components.
 
I found that the issue happens here:

``` 
onStartShouldSetResponderCapture={isIOS ? this._onTouchStart : null}
```
Removing this the plugin works properly.

**Comment by baijunjie** [comment]
Yes, must be above 0.46

**Comment by luco** [comment]
@baijunjie Removing that works on 0.44.3.

**Comment by baijunjie** [comment]
@luco The ReactNative version cannot be determined at runtime.
Do you have a better way?

**Comment by luco** [comment]
Creating a version for > 0.44.3 and another for <= 0.44.3.
Some repos do this way.
