### ISSUE TITLE
Multiline TextInput doesn't work in component

### ISSUE THREAD

**Issue by luco** [baijunjie/react-native-input-scroll-view#23]
When trying to use multiline component, it doesn't work (auto scroll) when the TextInput is inside a component.

Thoughts?

Thanks

**Comment by baijunjie** [comment]
Sorry, I need more feedback, like: version, your code snippet.

In addition, for the 0.50 after version, I lack the test, it may not be compatible with the new version.

I hope you can help me to locate the problem, such as which function did not work.

Thanks!

**Comment by baijunjie** [comment]
Due to a long time did not respond, temporarily closed.

**Comment by aquintiliano** [comment]
I've seen this bug happening as well
