### ISSUE TITLE
null is not an object (evaluating this._root._innerViewRef.measureInWindow)

### ISSUE THREAD

**Issue by IdealSystemsMCP** [baijunjie/react-native-input-scroll-view#24]
When the inputScrollView component is created, it runs the _onRef function to set the reference to the scrollview. 

But the _innerViewRef inside the reference is zero on Android. 

Workaround by adding a check: 
`if(typeof this._root._innerViewRef  !== 'undefined' && this._root._innerViewRef != null){
              this._root._innerViewRef.measureInWindow((x, y, width, height) => {
                  this._topOffset = y;
              });
            }`

**Comment by baijunjie** [comment]
Can you tell me about your react-native version?
Whether you can print `this._root` object to let me see.
I need to know if the original `_innerViewRef` changed its name?

**Comment by IdealSystemsMCP** [comment]
React native version 0.52.0. 

I see that the _innerViewRef is null inside the this._root object. 
When I reload, most of the time the _innerViewRef is not null anymore and everything works. Maybe the setTimeout 0 is not enough?

**Comment by baijunjie** [comment]
Try to see if it really solves the problem.
