### ISSUE TITLE
Wrong height of scrollview

### ISSUE THREAD

**Issue by aquintiliano** [baijunjie/react-native-input-scroll-view#27]
The height of the scrollview is increasing each time I swipe up (not on the InputText, out of it)
It only happens when the keyboard is shown and the height backs to its original value when the keyboard disappears

**Comment by baijunjie** [comment]
The height problem of scrollview doesn't seem to occur every time, and I don't see it.
Maybe I misunderstood English, and I didn't understand the problem.
