### ISSUE TITLE
Height undefined in _scrollToKeyboardRequest

### ISSUE THREAD

**Issue by IdealSystemsMCP** [baijunjie/react-native-input-scroll-view#31]
Because there is a debounce on the _onContentSizeChange event, not all textinput oncontentsizechange events callback will be executed and height will be undefined. 

If you do "undefined - 50", you receive "NaN" and no scroll will happen. 

Why is there a debounce on the _onContentSizeChange event?

**Comment by baijunjie** [comment]
On the real machine, debounce is required, and the `_onContentSizeChange` multiple execution causes other bugs.

You mean `event.nativeEvent.contentSize.height` possible is `undefined`?

**Comment by IdealSystemsMCP** [comment]
I've test this on a real machine. And found no issues when removing de debounce. 

> You mean event.nativeEvent.contentSize.height possible is undefined?

No, but when you render 3 (multiline) inputs (A,B,C) inside your inputscrollview.
And C has a default value with some text and line breaks. 
This is what happens:

1. Input A trigger a onContentSizeChange event with empty content (height of 18)
2. Input B trigger a onContentSizeChange event with empty content (height of 18)
3. Input C trigger a onContentSizeChange event with empty content (height of 18)
4. Input A trigger a onContentSizeChange event with content (height of 18)
5. Input B trigger a onContentSizeChange event with content (height of 18)
6. Input C trigger a onContentSizeChange event with content (height of 300 for example)

This 6 steps are not always in this order as they run next to each other. If you put a debounce on all events, you only receive one or two triggers. This means that one of the inputs has an undefined height and width. 

Kind regards

**Comment by baijunjie** [comment]
On the real machine, some of the bugs triggered by the JavaScript thread are hidden and can only be triggered in a few cases. In my project, if there is no debounce, the bug will appear. And after debugging, I'm sure that debounce cannot be removed.

The problem you described, I probably understand, should be multiple inputs using a debounce function at the same time, and I'll try to fix it.

**Comment by baijunjie** [comment]
@IdealSystemsMCP hey, try v1.6.7, see if solve your problem.
