### ISSUE TITLE
Doesn't work properly on a modal

### ISSUE THREAD

**Issue by luco** [baijunjie/react-native-input-scroll-view#36]
Again, this is a great plugin. Very useful. However I'm facing a issue when using it on a modal. I'm wrapping it on a flex container since I'm using a NavBar along.

```
<Modal>
<NavBar
                      title={('Sign up').toUpperCase()}
                      rightButton={(<TouchableOpacity onPress={this.props.close}><Text style={styles.topButton}>Cancelar</Text></TouchableOpacity>)}
                  />


                  <View style={{flex: 1}}>
                    <InputScrollView 
                    contentContainerStyle={{paddingTop: 20, paddingLeft: 10}}
                    >
```

But it doesn't scroll to desired position when it needs to scroll:

![image](https://user-images.githubusercontent.com/246373/43322965-a506eaee-9186-11e8-812a-f0f5a95a8a6b.png)
![image](https://user-images.githubusercontent.com/246373/43322973-a953836e-9186-11e8-932f-38798b6187f6.png)

Thoughts? Thanks in advance.

**Comment by baijunjie** [comment]
The main question is whether the method is valid in flex elements
```js
ScrollView.getScrollResponder().scrollResponderScrollNativeHandleToKeyboard()
```

**Comment by luco** [comment]
But that makes me use calculations, right? I mean, I gotta calculate screen height e to apply height to transition layer.

**Comment by baijunjie** [comment]
@luco 
```js
<View style={{flex: 1}}>
    <View style={{height: '100%'}}>
        <InputScrollView />
    </View>
</View>
```
Like this?

**Comment by luco** [comment]
@baijunjie I'll try this and let you know. Thanks!

**Comment by luco** [comment]
@baijunjie It's works. Thanks!
