### ISSUE TITLE
Scroll jumps when cursor is upper position and press Enter

### ISSUE THREAD

**Issue by themarvelme** [baijunjie/react-native-input-scroll-view#37]
Thanks for updating the repo to work well with new RN version.
But I found this bug. When I am typing in above the middle of the screen, It lost the current cursor position and scroll jumps down to make cursor position in the bottom area of the screen.
![aug-04-2018 01-16-59](https://user-images.githubusercontent.com/4304468/43658186-b7f6e708-978a-11e8-98bc-0f799125c4f9.gif)

Like you see in the gif, It happens when I press the "Enter" to change the line after I type "by november".

Here's the repo where you can replicate.
https://github.com/themarvelme/RN-input-scroll-view-bug-show

**Comment by baijunjie** [comment]
Yes, this problem was solved about before RN version 0.48.
But it won't work in the new version.

**Comment by themarvelme** [comment]
@baijunjie Thanks for the reply.
Do you have the plan to fix this in near future? 
I mean with new RN version. (0.56.0)

**Comment by baijunjie** [comment]
Of course, if there is a solution.

The problem now is that `getInstanceFromNode` is not available in the new version.  I could not get a ref instance of the input component through the target tag (which is a number), so I could not calculate the position of the input component

However, this plug-in is only a temporary solution to the imperfection of RN INPUT components. I believe that the official future will optimize this problem and my plug-in will not be used again.
