### ISSUE TITLE
Unable to resolve module 'react-native/Libraries/Renderer/shims/ReactNativeComponentTree'

### ISSUE THREAD

**Issue by jitinmaher** [baijunjie/react-native-input-scroll-view#4]
I am on React-native version **0.44.0**.

And I am getting this error while using this module.

I checked _react-native/Libraries/Renderer_ path in node_modules and i cannot find _/shims_ directory which has ReactNativeComponentTree. 

How should I fix this ? Helppp !!

**Comment by baijunjie** [comment]
Yes, in the 0.44 version, it's in this place
```js
import { getInstanceFromNode } from 'react-native/Libraries/Renderer/src/renderers/native/ReactNativeComponentTree.js'
```

You can modify it first, and I will collect enough information to make this module compatible.

**Comment by jitinmaher** [comment]
@baijunjie I changed the `getInstanceFromNode` line. Now the error is gone but the textinput are not clickable ie caret doesnot appear and I am not able to type anything.

Can you please help??

**Comment by baijunjie** [comment]
About 66 lines of source code
```jsx
<Animated.View style={{ marginBottom: this._contentBottomOffset }}
                                   onStartShouldSetResponderCapture={this._onStartShouldSetResponderCapture}>
                        {children}
                    </Animated.View>
```
Delete this sentence `onStartShouldSetResponderCapture={this._onStartShouldSetResponderCapture}`

You can solve your problem temporarily.
However, I recommend that you upgrade the react-native version.
