### ISSUE TITLE
event.nativeEvent.contentSize is undefined in IOS 10.2

### ISSUE THREAD

**Issue by feeyii** [baijunjie/react-native-input-scroll-view#42]
![a6c37b94-9c3c-43fc-9c1e-a34e1c860969](https://user-images.githubusercontent.com/8225400/47228372-9aa9c400-d3f7-11e8-9064-5cd1fcb62810.png)

no problem in ios 11 but error in ios 10

**Comment by baijunjie** [comment]
Hey, this is an unexpected accident. 
Could you debug and print out the event object for me? 
Thanks!
```js
    _onContentSizeChange = event => {
        const target = event.target || event.currentTarget;
        const inputInfo = this._getInputInfo(target);
console.log(event);
console.log(event.nativeEvent);
        inputInfo.width = event.nativeEvent.contentSize.width;
        inputInfo.height = event.nativeEvent.contentSize.height;
        if (inputInfo.text === undefined) {
            inputInfo.text = getProps(event._targetInst).value;
        }
        this._scrollToKeyboardRequest(true);
    };
```

**Comment by feeyii** [comment]
@baijunjie 

> _onContentSizeChange = event => {
        const target = event.target || event.currentTarget;
        const inputInfo = this._getInputInfo(target);
        console.log("------");
        console.log(event);
        console.log(event.nativeEvent);
        console.log("------");
        inputInfo.width = event.nativeEvent.contentSize.width;
        inputInfo.height = event.nativeEvent.contentSize.height;
        if (inputInfo.text === undefined) {
            inputInfo.text = getProps(event._targetInst).value;
        }
        this._scrollToKeyboardRequest(true);
    };

**Console Output:**

2018-10-20 11:10:40.667 [info][tid:com.facebook.react.JavaScript] ------
2018-10-20 11:10:40.669 [info][tid:com.facebook.react.JavaScript] {}
2018-10-20 11:10:40.670 [info][tid:com.facebook.react.JavaScript] undefined
2018-10-20 11:10:40.670 [info][tid:com.facebook.react.JavaScript] ------

**Comment by baijunjie** [comment]
Avoid error reporting for the time being, this may cause adjustment
failures
