### ISSUE TITLE
iOS scroll issue

### ISSUE THREAD

**Issue by wamphlett** [baijunjie/react-native-input-scroll-view#43]
I am experiencing a strange scroll is on iOS. When focusing an input or the content size changes, the screen scrolls up out of view. 

<img src="http://g.recordit.co/a0CnHgcRgo.gif">

I've debugged this somewhat and I can see the issue is coming from the `_onRef` function. Specifically, `y` in `measureInWindow` returns about 700 meaning that the scroll calculation is always out. If I add a delay to the `setTimeout`, e.g. 

```
setTimeout(() => {
            this._root._innerViewRef &&
            this._root._innerViewRef.measureInWindow((x, y) => {
                this._topOffset = y;
            });
        }, 1000);
```

then `y` becomes 25 and the scrolling works exactly as expected. Im not sure what the purpose of this `_onRef` function is and Im not confident that my solution is the best - feels hacky without knowing what this function is supposed to be doing. 

Perhaps I am doing something wrong somewhere else but I feel like I have exhausted all attempts to resolve this now. Are you able to help?

**Comment by baijunjie** [comment]
Very strange.

Sometimes `ScrollView` is not at the top of the page, it may be below `topBar`, so get this offset when you initialize.

The question is, why do you get 700 when initialize? It's either a `react-native` bug or you change its position after initialization.

Can you reproduce this problem in `__test__`?

**Comment by robertobrogi** [comment]
Hi, i have the same issue :( 
in Ios i have the very height scroll!

**Comment by baijunjie** [comment]
@robertobrogi Hi, I can't reproduce this problem. Can you provide a simple demo to reproduce this problem?

**Comment by baijunjie** [comment]
If there is any new feedback, please open it again

**Comment by stephan-J** [comment]
Hi @baijunjie , 

I have an error when using this module together with the screen transition module (react-navigation-transitions) .

Code is below.
After transition FirstScreen to MainScreen fromBottom, MainScreen has a problem.

- App.js
```
import { createAppContainer, createStackNavigator } from 'react-navigation';
import { fromBottom } from 'react-navigation-transitions';

import FirstScreen from './First';  //Temp first screen component
import MainScreen from './Main';  //example code for react-native-input-scroll-view component

const RootStack = createStackNavigator({
  First: FirstScreen,
  Main: MainScreen,
}, {
  navigationOptions: {
    header: null,
    gesturesEnabled: false,
  },
  initialRouteName: 'First',
  transitionConfig: () => fromBottom()
});


export default App = createAppContainer(RootStack);
```


- First.js
```
import React, {Component} from 'react';
import { View, Text, TouchableOpacity} from 'react-native';

export default class First extends Component {
    render() {
        return (
            <View>
                <TouchableOpacity
                onPress={()=>this.props.navigation.navigate('Main')}>
                    <Text>Touch to Main</Text>    
                </TouchableOpacity>
                
            </View>
        )
    }
}
```

- Main.js
```
export default class MainScreen extends Component<Props> {
  state = {
    text: '',
    textarea: '',
  };

  render() {
    const { text, textarea } = this.state;
    return (
      <View style={styles.container}>
        <InputScrollView>
          <View style={styles.placeholder} />
          <TextInput style={styles.input} value={text} />
          <TextInput style={styles.textarea}
                     value={textarea}
                     onChangeText={text => this.setState({ textarea: text })}
                     multiline />
        </InputScrollView>
      </View>
    );
  }
}
```

**Comment by baijunjie** [comment]
Thank you for your help.
I found the problem. The problem is that the screen enters the screen dynamically, and the automatic `topOffset` is wrong in the initial stage. Now try `v1.9.0` and set the `topOffset` props manually.

Suppose `TopBar.height=60`
```jsx
<InputScrollView topOffset={TopBar.height}>
         ...
</InputScrollView>
```
