### ISSUE TITLE
Custom Input with Multiline throws error on Change

### ISSUE THREAD

**Issue by luco** [baijunjie/react-native-input-scroll-view#44]
Hey,

While working with a custom Input with `multiline` prop, the Scroll View is throwing an error when I try to change the value:

![image](https://user-images.githubusercontent.com/246373/48439940-ad04ec80-e76e-11e8-9c75-1ce5d5d6b880.png)

The sourcemap pointed to these lines in `index.js`:

```
// onChange 在 onContentSizeChange 之前触发
    // onChange 在 onSelectionChange 之后触发
    _onChange = event => {
        const target = event.target || event.currentTarget;
        const inputInfo = this._getInputInfo(target);
        inputInfo.text = event.nativeEvent.text;
    }
```

This must be something while deepcloning, I'm not sure. Custom TextInput without `multiline` prop works properly.

I'm using version `1.7.0`

Thanks!

**UPDATE**

It seems that it's not returning the text value on `onChange`

**Comment by baijunjie** [comment]
at 232 line:
```js
    _getInputInfo(target) {
        return this._inputInfoMap[target] = this._inputInfoMap[target] || {};
    }
```
`this._getInputInfo(target)` It'll never be `undefined`, do you modify the source code?

Or try the latest version ` v1.7.3 `

**Comment by luco** [comment]
No I didn't. Also, I'm still getting the error with the `1.7.3`.

**Comment by baijunjie** [comment]
This error is currently circumvented

**Comment by luco** [comment]
@baijunjie Should I try `1.7.4`?

**Comment by baijunjie** [comment]
@luco Yes

**Comment by luco** [comment]
@baijunjie Worked perfectly. Thanks
