### ISSUE TITLE
Not able to get it working with Android

### ISSUE THREAD

**Issue by arrygoo** [baijunjie/react-native-input-scroll-view#45]
Here's all of my code and I'm using a Pixel 3 XL. As you can see the text hides behind the keyboard, and a smaller issue is that it flickers. 
```
import React from 'react';
import { StyleSheet, Text, View, TextInput } from 'react-native';
import InputScrollView from 'react-native-input-scroll-view';

export default class App extends React.Component {
  state = {
    text: 'Start typing..',
    textareaHeight: null
  };

  render() {
    const { text, textareaHeight } = this.state;
    return (
      <InputScrollView>
        <TextInput />
        <TextInput />
        <TextInput
          style={{ height: textareaHeight }}
          value={text}
          onChangeText={text => this.setState({ text })}
          onContentSizeChange={this._onContentSizeChange}
          multiline
        />
      </InputScrollView>
    );
  }

  _onContentSizeChange = ({ nativeEvent: event }) => {
    this.setState({ textareaHeight: event.contentSize.height });
  };
}
```

My Package.json:
```

  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^31.0.2",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",
    "react-native-input-scroll-view": "^1.8.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}
```

![6v0cat9](https://user-images.githubusercontent.com/965429/50550089-896f0600-0c37-11e9-8c59-d9b6fcd46dfc.gif)

**Comment by baijunjie** [comment]
In the new version, Android devices don't seem to need this code anymore `style={{ height: textareaHeight }}`.

**Comment by baijunjie** [comment]
You can try a different simulator to see if this problem exists on most devices.

I need more feedback, including the react-native version you used. If it's not the latest version, I suggest you upgrade first.

**Comment by arrygoo** [comment]
@baijunjie I'm actually using a physical device, on Expo 31 which uses React Native 0.57.

I tested with Galaxy S6 and Pixel 3XL, both of them have the same behaviour as in the text goes behind the keyboard. Same code works for iOS though. What can I do to help with debugging the issue?

**Comment by arrygoo** [comment]
Hmm even in this snack it works perfectly of you pick iOS but doesn't work with Android: 
https://snack.expo.io/@arrygoo/react-native-input-scroll-view

**Comment by baijunjie** [comment]
Hi @arrygoo The core of this plugin is `scrollResponderScrollNativeHandleToKeyboard` using this method, and the method is executed successfully in the [demo](https://snack.expo.io/@baijunjie/react-native-input-scroll-view), but he did not produce the desired effect.

I don't know why it doesn't work in this android emulator. But in my computer, `scrollResponderScrollNativeHandleToKeyboard` in all of the android emulator can work normally. (The emulator in Android Studio doesn't have the Pixel 3XL, only the Pixel 2XL)

This might be related to the `react-native` Android Settings file, but I don't know where it is.

If you can find out why `scrollResponderScrollNativeHandleToKeyboard` is not working, that would be great.

**Comment by arrygoo** [comment]
@baijunjie I forked your package, and this fixed it for me on Android!:
`<KeyboardAvoidingView behavior={isIOS ? 'padding' : null}>` 
---> 
`<KeyboardAvoidingView keyboardVerticalOffset={30} behavior={'padding'}>`

Maybe Expo's React Native has a slightly different `KeyboardAvoidingView` than plain react native?

This issue might be related but I'm not sure:
https://github.com/expo/expo/issues/2172

**Comment by baijunjie** [comment]
Great.

The culprit was him `behavior={isIOS ? 'padding' : null}`, once because of it, android devices don't work, that's why we have this expression.

Ok, it doesn't seem to be needed now, I'll fix it as soon as possible. Thanks!

**Comment by baijunjie** [comment]
I'm sorry, the question may not be that simple. `behaviors={ 'padding' }` some Android devices don't work, perhaps as official said: "Android may concerns better when given no behaviors prop at all, whereas iOS is the opposite."

I can only hold on to this version until I find a better solution. 

You can temporarily solve your problem with your own fork.
