### ISSUE TITLE
iOS scroll issue

### ISSUE THREAD

**Issue by stephan-J** [baijunjie/react-native-input-scroll-view#48]
Hi @baijunjie , 

I have an same issue about previous issue https://github.com/baijunjie/react-native-input-scroll-view/issues/43#issue-379830720
When I using this module together with the screen transition module (react-navigation-transitions) .

Error Code is below.
After transition FirstScreen to MainScreen fromBottom, MainScreen has a problem.

- App.js
```
import { createAppContainer, createStackNavigator } from 'react-navigation';
import { fromBottom } from 'react-navigation-transitions';

import FirstScreen from './First';  //Temp first screen component
import MainScreen from './Main';  //example code for react-native-input-scroll-view component

const RootStack = createStackNavigator({
  First: FirstScreen,
  Main: MainScreen,
}, {
  navigationOptions: {
    header: null,
    gesturesEnabled: false,
  },
  initialRouteName: 'First',
  transitionConfig: () => fromBottom()
});


export default App = createAppContainer(RootStack);
```

- First.js
```
import React, {Component} from 'react';
import { View, Text, TouchableOpacity} from 'react-native';

export default class First extends Component {
    render() {
        return (
            <View>
                <TouchableOpacity
                onPress={()=>this.props.navigation.navigate('Main')}>
                    <Text>Touch to Main</Text>    
                </TouchableOpacity>
                
            </View>
        )
    }
}
```

- Main.js
```
export default class MainScreen extends Component<Props> {
  state = {
    text: '',
    textarea: '',
  };

  render() {
    const { text, textarea } = this.state;
    return (
      <View style={styles.container}>
        <InputScrollView>
          <View style={styles.placeholder} />
          <TextInput style={styles.input} value={text} />
          <TextInput style={styles.textarea}
                     value={textarea}
                     onChangeText={text => this.setState({ textarea: text })}
                     multiline />
        </InputScrollView>
      </View>
    );
  }
}
```

**Comment by baijunjie** [comment]
Hi, I'm not sure what went wrong, I need more detailed error information.

**Comment by stephan-J** [comment]
I'm used 2 RN module, `react-native-input-scroll-view` and `react-navigation-transitions`.

1. I had screen transition from 'FirstScreen' to 'MainScreen' via `react-native-input-scroll-view` (use fromBottom function)
2. In MainScreen(is same your example code) touch textinput
3. Same error with https://github.com/baijunjie/react-native-input-scroll-view/issues/43#issue-379830720 

It's occur only fromBottom function not fromLeft, fromRight etc.

I think that error is about conflict to `react-native-input-scroll-view` and `react-navigation-transitions`.

**Comment by baijunjie** [comment]
@stephan-J HI, This issue should have something to do with `scrollResponderScrollNativeHandleToKeyboard()` compatibility, can you reproduce it in https://snack.expo.io/
Thanks.

**Comment by stephan-J** [comment]
Hi @baijunjie , You can see in 
https://snack.expo.io/@jsc/simple-project

**Comment by baijunjie** [comment]
Thank you for your help.
I found the problem. The problem is that the screen enters the screen dynamically, and the automatic `topOffset` is wrong in the initial stage. Now try `v1.9.0` and set the `topOffset` props manually.
