### ISSUE TITLE
PR allowed

### ISSUE THREAD

**Issue by juanmunozg** [baijunjie/react-native-input-scroll-view#5]
HI! Do you think I can get access and push to your repo in order to create a PR for Android fixes?

Thanks

**Comment by baijunjie** [comment]
Yes, sure

**Comment by juanmunozg** [comment]
ERROR: Permission to baijunjie/react-native-input-scroll-view.git denied to juanmunozg.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by baijunjie** [comment]
I'm not good at handling this type of problem, or you can Fork the repository, then Pull requests
