### ISSUE TITLE
Scroll issues when view at bottom

### ISSUE THREAD

**Issue by azmatullahqau** [baijunjie/react-native-input-scroll-view#52]
Views hide below the scroll view,  any help?

**Comment by baijunjie** [comment]
HI, please reproduce it using https://snack.expo.io/

**Comment by azmatullahqau** [comment]
I have solved the problem by wrapping InputScrollView within ` <View style={{flex: 1}}>` then its work fine. Otherwise, it hides the other views below scroll due to 100% height.
