### ISSUE TITLE
Accessing view manager configs directly off UIManager via UIManager['AndroidTextInput'] is no longer supported. Use UIManager.getViewManagerConfig('AndroidTextInput') instead.

### ISSUE THREAD

**Issue by kufii** [baijunjie/react-native-input-scroll-view#54]
Hey, when running with react native version 0.59, the following warning is shown:

Accessing view manager configs directly off UIManager via UIManager['AndroidTextInput'] is no longer supported. Use UIManager.getViewManagerConfig('AndroidTextInput') instead.

**Comment by baijunjie** [comment]
try v1.9.2
