### ISSUE TITLE
Scrollview scrolls up on focus

### ISSUE THREAD

**Issue by woodpav** [baijunjie/react-native-input-scroll-view#55]
On both Android and iOS the keyboard scrolls up when I focus on an input.

My view is roughly

    <View style={{ flex: 1 }}>
       <ScrollView style={{ flex: 1 }}>
         <View style={{ height: 1000 }} />
         <TextInput />
       </ScrollView>
       <View style={{ height: 100 }} />
    </View>

Do I need to mess around with offset props or do I need to build a demo? Great repo btw, thank you.

**Comment by baijunjie** [comment]
Please use `https://snack.expo.io/` to make the smallest demo.

**Comment by woodpav** [comment]
Here is a snack: https://snack.expo.io/SJbdHEjp4 and here is a repo to clone: https://github.com/woodpav/keyboard-test

The snack behaves as expected but when you clone the repo and put it onto the simulator it does work.

Sometimes the view changes to the right size but most of the time the TextInput moves down and hides below the keyboard.

**Comment by baijunjie** [comment]
I didn't find anything unusual, maybe I didn't understand what you meant.
Will Android and iOS have the same problem?

**Comment by baijunjie** [comment]
On android devices, you may need to add them manually:
```jsx
<InputScrollView keyboardAvoidingViewProps={{ behavior: "padding" }}>
...
```

**Comment by woodpav** [comment]
I am experiencing it on iOS and Android. It happens after I refresh the app at least once. I am also experiencing it on a physical device.

To reproduce:

1) `git clone https://github.com/woodpav/keyboard-test`
2) `cd keyboard-test && yarn ios`
3) Scroll down and click "Hi" placeholder
4) Refresh app until "Hi" TextInput moves below the keyboard instead of moving above the keyboard like it should.

![keyboard-test](https://user-images.githubusercontent.com/22600052/58530786-d8907700-8194-11e9-97e3-49c118e5f8c5.gif)

**Comment by baijunjie** [comment]
Unfortunately, I can't run your project.
In IOS, debug mode and release mode may have different effects. Is there the same problem in release mode?

**Comment by baijunjie** [comment]
@woodpav Please try v1.9.3
