### ISSUE TITLE
Scrolling to cursor and scrolling to bottom upon editing TextInput doesn't work if first layer of components in the InputScrollView doesn't have 'multiline' set to true when props are handled in lower components

### ISSUE THREAD

**Issue by YoranRoels** [baijunjie/react-native-input-scroll-view#57]
### Description
When multiline isn't added in the first layer of components in the InputScrollView it seems that only scrolling down to the bottom of the TextInput works but scrolling to cursor and scrolling when adding more text doesn't get handled.

This seems to be have been raised in issue 26 (https://github.com/baijunjie/react-native-input-scroll-view/issues/26) but it might have been misunderstood since there was some confusion in that thread.

I first thought that the state and such had to be handled in the top-most component for it to work but it's ONLY the `multiline={true}` prop that allows for the passing of props all the way to your lower components (like you do in the example).

### Example
I've replicated what I mean with snack.expo.io in its most basic form.
This is what doesn't work: https://snack.expo.io/H1x-fHTpV
This is what works: https://snack.expo.io/ryLyzHppE
The main difference being that the state is now handled in the lower component.

### Some final words
I'd like to add that I absolutely LOVE this dependency and it's a perfect fit for our application, this was the only issue blocking me from using it all over our application, but using `multiline={true}` on the first layer of components seems like a decent temporary fix.
It still doesn't seem like ideal behaviour but I can live with it.

**Be sure to let me know if I can provide any extra info.**

**Comment by baijunjie** [comment]
Your question should be related to this code:
```js
    // line 181
    _cloneDeepComponents(Component) {
        if (Component instanceof Array) {
            return Component.map(subComponent => this._cloneDeepComponents(subComponent));
        } else if (Component && Component.props && Component.props.children) {
            const newComponent = { ...Component };
            newComponent.props = { ...Component.props };
            newComponent.props.children = this._cloneDeepComponents(Component.props.children);
            return newComponent;
        } else if (Component && Component.props && Component.props.multiline) {
            const newComponent = { ...Component };
            newComponent.props = { ...Component.props };
            return this._addMultilineHandle(newComponent);
        } else {
            return Component;
        }
    }
```

If I cannot traverse the children of the component, I will not be able to add `_addMultilineHandle` to it.
So it doesn't work.

**Comment by YoranRoels** [comment]
I see what you mean, we can close this for now since there is a good solution.
I just wanted to make people aware of this because I think related issues were opened for this since people say you "can't pass props to children" which is false, using multiline "fixes" this.

Thanks for the explanation!
