### ISSUE TITLE
TextInput doesn't autoscroll down if you connect a hardware keyboard

### ISSUE THREAD

**Issue by dsernst** [baijunjie/react-native-input-scroll-view#69]
From the readme:

> When the multiline TextInput create new line, the new line will automatically adjust to the top of the keyboard.

But this doesn't appear to be working if the software keyboard is hidden, because of another hardware keyboard (Cmd + K) in iOS Simulator, or after connecting a Bluetooth keyboard to your device.

Here are 2 gifs to illustrate expected vs actual:

### Autoscroll works when keyboard visible:

<img src="https://user-images.githubusercontent.com/6340841/78211042-ce986e00-7460-11ea-8876-2c74c9675179.gif" width="300px" />

### But autoscroll stops working when the keyboard isn't visible (bc of another hardware keyboard)

<img src="https://user-images.githubusercontent.com/6340841/78211047-d22bf500-7460-11ea-91d6-fa2ac6dcbfa1.gif" width="300px" />

I also tested this in `debug` mode vs `release` mode (as [recommended here](https://github.com/baijunjie/react-native-input-scroll-view/issues/55#issuecomment-497552628)), & on a physical iPhone w/ a Bluetooth keyboard connected, and seeing it reproduce every time.

#### Version info:

```
react-native: 0.62.0
react-native-input-scroll-view: 1.9.5
iOS: 13.4
```

**Comment by dsernst** [comment]
Looks like the relevant line is: https://github.com/baijunjie/react-native-input-scroll-view/blob/8bc6d483f8709445a033fa75a437d4ad8fefc6e2/index.js#L283

Commenting it out fixes this issue, and allows the autoscroll to continue working w/ a hardware keyboard active.

Would this lead to unintended consequences? I don't see why that conditional was added.

**Comment by baijunjie** [comment]
Thank you for finding the problem. Since it has been a long time, I am not sure whether it will cause any side effects. I can offer an option to help you solve the problem.

**Comment by baijunjie** [comment]
@dsernst Please try `v1.10.0`
