### ISSUE TITLE
Error with Expo SDK37

### ISSUE THREAD

**Issue by outaTiME** [baijunjie/react-native-input-scroll-view#70]
Im using this component in the following way:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/140472/78595015-a5405f00-781f-11ea-97c1-a57696dbbc44.png">

and i get this issue:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/140472/78594961-8e017180-781f-11ea-96f0-62725d9136be.png">

Something boken in with the last release?

**Comment by baijunjie** [comment]
The new version only adds an option and does not affect the original functionality.
You can learn more about the changes in the latest commit.
Will this error not occur in v1.9.4?

**Comment by rikur** [comment]
I think newer react-native broke the the way this library handles the refs. I couldn't find the exact change that caused it, but this diff fixed it for me:

```
diff --git a/node_modules/react-native-input-scroll-view/index.js b/node_modules/react-native-input-scroll-view/index.js
index 9f0c9aa..40ec8a3 100644
--- a/node_modules/react-native-input-scroll-view/index.js
+++ b/node_modules/react-native-input-scroll-view/index.js
@@ -89,8 +89,12 @@ export default class extends PureComponent {
         measureInputWidth: 0,
     };
 
+    constructor(props) {
+        super(props);
+        this._root = React.createRef();
+    }
+
     componentDidMount() {
-        this._root = null;
         this._curFocus = null;
         this._measureCallback = null;
         this._keyboardShow = false;
@@ -268,15 +272,15 @@ export default class extends PureComponent {
             this._root = this._root._component;
         }
 
-        const getTopOffset = () => {
+        const getTopOffset = (innerViewRef) => {
             this.props.topOffset === undefined &&
-            this._root._innerViewRef &&
-            this._root._innerViewRef.measureInWindow((x, y) => {
+            innerViewRef &&
+            innerViewRef.measureInWindow((x, y) => {
                 if (y > 0) this._topOffset = y;
             });
         };
 
-        setTimeout(getTopOffset);
+        setTimeout(() => getTopOffset(root._innerViewRef));
         // 如果屏幕是带动画进入，那么初次获取的位置偏移量并不准确
         // 这时最好通过 topOffset 属性来手动设定 topBar 的偏移量
     };
```

**Comment by baijunjie** [comment]
Hi @rikur, Thank you for finding the solution.

I'm not sure if this code is supported by older versions? What did it do? Is there an official explanation?
```
React.createRef()
```

**Comment by rikur** [comment]
I'm sorry I don't have the time to test it against an older react-native.. but you could try something like:
```this._root = typeof React.createRef === 'function' ? React.createRef() : null;```

**Comment by rikur** [comment]
One more quick diff that fixes android for me:

```
     _onSelectionChange = debounce(event => {
-        const target = event.target || event.currentTarget;
+        const target = event.target || event.currentTarget || event._targetInst.stateNode._nativeTag;
```

**Comment by baijunjie** [comment]
Please try `v1.10.1`
