### ISSUE TITLE
Cannot read property 'uiViewClassName' of undefined

### ISSUE THREAD

**Issue by jrz90000** [baijunjie/react-native-input-scroll-view#8]
这个项目很棒，一直用着挺好的。
今天升级react-native到0.49.3后，点击我的输入框就会提示“Cannot read property 'uiViewClassName' of undefined”
目前还不支持最新新版本吗？这个该怎么解决呢？

![061f3fd4f729f1b163e528c8067d71dc](https://user-images.githubusercontent.com/7508776/31506433-0a2ef92a-af3d-11e7-97c0-496afe2a35b0.jpg)
<img width="965" alt="qq20171012-235422 2x" src="https://user-images.githubusercontent.com/7508776/31506434-0a759222-af3d-11e7-9639-76a144e51758.png">

**Comment by baijunjie** [comment]
看来官方在0.49中移动了 `uiViewClassName` 属性的位置，今晚我会出一个兼容版本

**Comment by baijunjie** [comment]
尝试 v1.3.2

**Comment by jrz90000** [comment]
已经正常，谢谢。
